// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using BupaAcibademWebApi.Models;

#nullable disable

namespace BupaAcibademWebApi.Data
{
    public partial class BupaAcibademDBContext : DbContext
    {
        public BupaAcibademDBContext()
        {
        }

        public BupaAcibademDBContext(DbContextOptions<BupaAcibademDBContext> options)
            : base(options)
        {
        }


        public virtual DbSet<Product> Products { get; set; }

        public virtual DbSet<OrderTable> OrderTables { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Turkish_CI_AS");

            modelBuilder.Entity<OrderTable>(entity =>
            {
                entity.ToTable("OrderTable");

                entity.Property(e => e.CardHolderFirstNameLastName).HasMaxLength(50);

                entity.Property(e => e.CardValidationValue).HasMaxLength(50);

                entity.Property(e => e.City)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.CreditCardNumber).HasMaxLength(50);

                entity.Property(e => e.Email)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.FirstName)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.LastName)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.PaymentType).HasMaxLength(50);

                entity.Property(e => e.PhoneNumber)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.PolicyName)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.PolicyPrice)
                    .IsRequired()
                    .HasMaxLength(50);

                entity.Property(e => e.ValidThru).HasMaxLength(50);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}