// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BupaAcibademWebApi.Models
{
    public partial class OrderTable
    {
        public int Id { get; set; }
        public string PolicyName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string City { get; set; }
        public string Email { get; set; }
        public string CardHolderFirstNameLastName { get; set; }
        public string CreditCardNumber { get; set; }
        public string ValidThru { get; set; }
        public string CardValidationValue { get; set; }
        public string PaymentType { get; set; }
        public string PolicyPrice { get; set; }
    }
}